releases:
  dockerhub:
    - repo: nginx
    - repo: ghost
    - repo: telegraf

    - owner: portainer
      repo:  portainer

    - owner:  fluent
      repo:   fluentd
      filter: '^v[0-9]+\.[0-9]+\.[0-9]+$'

  github:
    - owner:  docker
      repo:   docker-ce
      filter: '[0-9]+\.[0-9]+\..+'

    - owner: docker
      repo:  docker-py

    - owner:  prometheus
      repo:   prometheus
      filter: '^v?[0-9]+\.[0-9]+\.[0-9]+($| .*)'

    - owner:  prometheus
      repo:   node_exporter
      filter: '^v?[0-9]+\.[0-9]+\.[0-9]+($| .*)'

    - owner: grafana
      repo:  grafana
      filter: '^v[0-9]+\.[0-9]+\.[0-9]+$'

  jetbrains:
    - name: go
      alias: GoLand

    - name: iiu
      alias: IntelliJ IDEA

    - name: pcp
      alias: PyCharm
